import { contextBridge, ipcRenderer } from 'electron';
import type { GitVistaApi } from '../shared/types';
const api: GitVistaApi = {
  settings: () => ipcRenderer.invoke('gv:settings'),
  setTheme: theme => ipcRenderer.invoke('gv:theme', theme),
  updatePreferences: preferences => ipcRenderer.invoke('gv:preferences', preferences),
  browseGitPath: () => ipcRenderer.invoke('gv:git:browse'),
  testGitPath: gitPath => ipcRenderer.invoke('gv:git:test', gitPath),
  getGitIdentity: repo => ipcRenderer.invoke('gv:identity:get', repo),
  setGitIdentity: (repo, identity) => ipcRenderer.invoke('gv:identity:set', repo, identity),
  openRepository: (path, singleRepository) => ipcRenderer.invoke('gv:open', path, singleRepository),
  openWorkspace: path => ipcRenderer.invoke('gv:workspace:open', path),
  workspaceOverview: root => ipcRenderer.invoke('gv:workspace:overview', root),
  workspaceDirectory: (root, relative) => ipcRenderer.invoke('gv:workspace:directory', root, relative),
  workspaceFile: (root, relative) => ipcRenderer.invoke('gv:workspace:file', root, relative),
  workspacePushPreview: (root, repos, includeChanges) => ipcRenderer.invoke('gv:workspace:preview', root, repos, includeChanges),
  workspaceBatch: (root, request) => ipcRenderer.invoke('gv:workspace:batch', root, request),
  onWorkspaceProgress: listener => { const handler = (_event: Electron.IpcRendererEvent, progress: Parameters<typeof listener>[0]) => listener(progress); ipcRenderer.on('gv:workspace:progress', handler); return () => ipcRenderer.removeListener('gv:workspace:progress', handler); },
  forgetRepository: path => ipcRenderer.invoke('gv:forget', path),
  cloneRepository: (url, parent, name, credentials) => ipcRenderer.invoke('gv:clone', url, parent, name, credentials),
  chooseDirectory: () => ipcRenderer.invoke('gv:directory'),
  setRepositoryCredentials: (repo, remote, credentials) => ipcRenderer.invoke('gv:credentials', repo, remote, credentials),
  desktopState: () => ipcRenderer.invoke('gv:desktop:state'),
  desktopCommand: command => ipcRenderer.invoke('gv:desktop:command', command),
  onDesktopState: listener => { const handler = (_event: Electron.IpcRendererEvent, state: Parameters<typeof listener>[0]) => listener(state); ipcRenderer.on('gv:desktop:state', handler); return () => ipcRenderer.removeListener('gv:desktop:state', handler); },
  onRepositoryRefresh: listener => { const handler = () => listener(); ipcRenderer.on('gv:repository:refresh', handler); return () => ipcRenderer.removeListener('gv:repository:refresh', handler); },
  initRepository: path => ipcRenderer.invoke('gv:init', path),
  query: (repo, query) => ipcRenderer.invoke('gv:query', repo, query),
  action: (repo, action) => ipcRenderer.invoke('gv:action', repo, action),
  exportPatch: (repo, ref) => ipcRenderer.invoke('gv:export', repo, ref),
  revealPath: (repo, relative) => ipcRenderer.invoke('gv:reveal', repo, relative),
  windowControl: action => ipcRenderer.send('gv:window', action),
};
contextBridge.exposeInMainWorld('gitvista', api);
